### ISSUE TITLE
Missing package-lock.json

### ISSUE THREAD

**Issue by skywarth** [Ayrlin-Renata/blade-heart#1]
Hi there,

I've seen that you've used [Vite Github Pages Deployer](https://github.com/skywarth/vite-github-pages-deployer) and encountered some error while using it.

[In this action run](https://github.com/Ayrlin-Renata/blade-heart/actions/runs/7707800446/job/21005611810) you received an error from npm, indicating "The npm ci command can only install with an existing package-lock.json". This is due to the fact that my package used npm ci to install the project dependencies, this is the designated method for CI installations. 

**You may resolve this issue by simply uploading package-lock.json in your repository**, you may have it in gitignore at the moment.

Documentation also has a description on how to identify and resolve this error: https://github.com/skywarth/vite-github-pages-deployer#63-package-lockjson-is-not-present-when-using-npm-as-package-manager-preferrence

Hope it helps.

**Comment by Ayrlin-Renata** [comment]
hey, thanks for looking into it!

i'll be sure to give it a try after i've resolved some other major issues
i'm having with the project at the moment

I appreciate the pointers :3
